version: '2'
services:
  jhipstersamplebruteapplication-mongodb:
    image: mongo:4.2.3
    ports:
      - '27017:27017'
    # volumes:
    #     - ~/volumes/jhipster/jhipsterSampleBruteApplication/mongodb/:/data/db/
